name: build
on: [push, pull_request]
jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu, macos, windows]
    name: test [${{ matrix.os }}]
    runs-on: ${{ matrix.os }}-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v1
      - name: Set up rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: clippy
          override: true
      - name: Run clippy
        uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-features
      - name: Run cargo build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --all-features
      - name: Run cargo test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --all-features --no-fail-fast

